### ISSUE TITLE
Spectrogram display in tracedisplay doesn't update when masked data is present

### ISSUE THREAD

**Issue by stefanmaar** [stefanmaar/psysmon#9]
When screening through the data using the spectrogram view, the views are not updated when stepping to the next timewindow if some data in that time window contains masked data.

There always seems to be a missmatch by 1 sample.

```
Traceback (most recent call last):
  File "/home/stefan/01_gtd/04_aktuelleProjekte/2012-0007_pSysmon/01_src/psysmon/lib/psysmon/core/gui.py", line 3367, in <lambda>
    lambda evt, curPlugin=curPlugin : self.on_view_tool_clicked(evt, curPlugin),
  File "/home/stefan/01_gtd/04_aktuelleProjekte/2012-0007_pSysmon/01_src/psysmon/lib/psysmon/core/gui.py", line 3575, in on_view_tool_clicked
    self.update_display()
  File "/home/stefan/01_gtd/04_aktuelleProjekte/2012-0007_pSysmon/01_src/psysmon/lib/psysmon/packages/tracedisplay/tracedisplay.py", line 805, in update_display
    curPlugin.plot(self.displayManager, self.dataManager)
  File "/home/stefan/01_gtd/04_aktuelleProjekte/2012-0007_pSysmon/01_src/psysmon/lib/psysmon/packages/tracedisplay/plugins_views.py", line 983, in plot
    self.plotStation(displayManager, dataManager, displayManager.showStations)
  File "/home/stefan/01_gtd/04_aktuelleProjekte/2012-0007_pSysmon/01_src/psysmon/lib/psysmon/packages/tracedisplay/plugins_views.py", line 991, in plotStation
    self.plotChannel(displayManager, dataManager, curStation.channels)
  File "/home/stefan/01_gtd/04_aktuelleProjekte/2012-0007_pSysmon/01_src/psysmon/lib/psysmon/packages/tracedisplay/plugins_views.py", line 1015, in plotChannel
    curView.plot(curStream,
  File "/home/stefan/01_gtd/04_aktuelleProjekte/2012-0007_pSysmon/01_src/psysmon/lib/psysmon/packages/tracedisplay/plugins_views.py", line 1064, in plot
    timeArray = np.ma.array(timeArray[:-1], mask=trace.data.mask)
  File "/home/stefan/python-environments/psysmon_dev3.8/lib/python3.8/site-packages/numpy/ma/core.py", line 6559, in array
    return MaskedArray(data, mask=mask, dtype=dtype, copy=copy,
  File "/home/stefan/python-environments/psysmon_dev3.8/lib/python3.8/site-packages/numpy/ma/core.py", line 2908, in __new__
    raise MaskError(msg % (nd, nm))
numpy.ma.core.MaskError: Mask and data not compatible: data size is 60000, mask size is 60001.

```

**Comment by stefanmaar** [comment]
Fixed the issue.
